#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO_SLUG="jcampos90/my-portfolio"
CUSTOM_DOMAIN="portfolio.jcdevsolutions.com"

cd "$(dirname "$0")/.."

banner "Deploy the portfolio to Cloudflare Pages"

# ── Stage 1 ────────────────────────────────────────────────────────────────
stage "GitHub: create the repository and push"

say "The repository does not exist on GitHub yet. Create it, then push."
open_url "https://github.com/new?name=my-portfolio&visibility=private"
step "Repository name: my-portfolio"
step "Visibility: Private (you can flip this to Public once v1 reads well)"
step "Do NOT add a README, .gitignore, or licence — this repo already has commits."
step "Select Create repository."
pause "Press Enter once the empty repository exists"

if git remote get-url origin >/dev/null 2>&1; then
  note "remote origin already set: $(git remote get-url origin)"
else
  git remote add origin "git@github.com:${REPO_SLUG}.git"
  printf '  %s✓%s added remote origin → git@github.com:%s.git\n' "$GREEN" "$RESET" "$REPO_SLUG"
fi

note "Current branch is renamed to main to match Cloudflare's production branch."
git branch -M main

if confirm "Push $(git rev-list --count HEAD) commit(s) to GitHub now?"; then
  if git push -u origin main; then
    printf '  %s✓%s pushed\n' "$GREEN" "$RESET"
  else
    warn "push failed — check that the repo exists and your SSH key is on the account"
    SKIPPED+=("push to git@github.com:${REPO_SLUG}.git")
  fi
else
  SKIPPED+=("push to GitHub (git push -u origin main)")
fi

# ── Stage 2 ────────────────────────────────────────────────────────────────
stage "Cloudflare Pages: create the project"

say "Connect Pages to the repository you just pushed."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Select Create application."
step "Select the Pages tab."
step "Select Import an existing Git repository."
step "Pick jcampos90/my-portfolio, then select Begin setup."
printf '\n'
say "In Build settings, set the Framework preset to Next.js (Static HTML Export)."
note "That preset fills in exactly what this repo needs:"
note "    Production branch   main"
note "    Build command       npx next build"
note "    Build directory     out"
warn "Do not pick plain \"Next.js\" — that preset assumes a server and will fail on a static export."
printf '\n'
say "Leave environment variables empty. There are none: analytics is enabled in Stage 5"
say "from the dashboard, so this repo needs no token."
step "Select Save and deploy, and wait for the first build to finish."
pause "Press Enter once the first deployment has succeeded"

ask CF_PAGES_PROJECT "Your Pages project name (the bit before .pages.dev):"
write_env CF_PAGES_PROJECT "$CF_PAGES_PROJECT"

# ── Stage 3 ────────────────────────────────────────────────────────────────
stage "Verify the first deploy"

say "Check the site works on Cloudflare's URL before adding a custom domain."
open_url "https://${CF_PAGES_PROJECT}.pages.dev"
step "The page renders with your name and the purple accents."
step "Download CV works and opens a 2-page PDF."
step "Nothing looks unstyled — if it does, the CSS failed and the build needs attention."
printf '\n'
note "Also worth a look:"
note "    https://${CF_PAGES_PROJECT}.pages.dev/robots.txt"
note "    https://${CF_PAGES_PROJECT}.pages.dev/sitemap.xml"
if ! confirm "Does the site look right?"; then
  warn "Fix the deploy before continuing, then re-run this wizard."
  SKIPPED+=("custom domain — first deploy not verified")
fi

# ── Stage 4 ────────────────────────────────────────────────────────────────
stage "Cloudflare: attach the custom domain"

say "Point ${CUSTOM_DOMAIN} at this Pages project."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Select the ${CF_PAGES_PROJECT} project."
step "Go to Custom domains and select Set up a custom domain."
step "Enter ${CUSTOM_DOMAIN} and confirm."
printf '\n'
note "jcdevsolutions.com already uses Cloudflare nameservers, so Cloudflare creates the"
note "DNS record itself. You do not need to add a CNAME by hand."
note "Certificate issuance usually takes under a minute."
pause "Press Enter once the domain shows as Active"

if getent hosts "$CUSTOM_DOMAIN" >/dev/null 2>&1; then
  printf '  %s✓%s %s resolves\n' "$GREEN" "$RESET" "$CUSTOM_DOMAIN"
else
  warn "$CUSTOM_DOMAIN does not resolve yet — DNS or the certificate may still be propagating"
  SKIPPED+=("confirm $CUSTOM_DOMAIN resolves")
fi

# ── Stage 5 ────────────────────────────────────────────────────────────────
stage "Cloudflare: enable Web Analytics"

say "One toggle. No code, no token, no cookie banner."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Select the ${CF_PAGES_PROJECT} project."
step "Go to Metrics and select Enable under Web Analytics."
printf '\n'
note "Cloudflare injects the beacon on the next deployment. Because of that, this repo"
note "deliberately contains no analytics snippet — adding one would double-count visits."
note "Metrics appear at https://dash.cloudflare.com/?to=/:account/web-analytics"

# ── Stage 6 ────────────────────────────────────────────────────────────────
stage "Verify the live site"

say "Final check on the real domain."
printf '\n'

check() {
  local label="$1" url="$2" expect="$3" body code
  body=$(curl -sL --max-time 25 -w '\n%{http_code}' "$url" 2>/dev/null || printf '\n000')
  code=$(printf '%s' "$body" | tail -n1)
  if [[ "$code" == "200" && ( -z "$expect" || "$body" == *"$expect"* ) ]]; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$label"
  else
    printf '  %s✗%s %s (HTTP %s)\n' "$RED" "$RESET" "$label" "$code"
    SKIPPED+=("verify: $label")
  fi
}

check "homepage returns 200 and names Juan Campos" "https://${CUSTOM_DOMAIN}/" "Juan Campos"
check "robots.txt served"                            "https://${CUSTOM_DOMAIN}/robots.txt" "Sitemap"
check "sitemap.xml served"                           "https://${CUSTOM_DOMAIN}/sitemap.xml" "${CUSTOM_DOMAIN}"

pdf_headers=$(curl -sIL --max-time 25 "https://${CUSTOM_DOMAIN}/cv/Juan_Campos_CV.pdf" 2>/dev/null || true)
if [[ "$pdf_headers" == *"200"* && "$pdf_headers" == *"application/pdf"* ]]; then
  printf '  %s✓%s CV PDF served as application/pdf\n' "$GREEN" "$RESET"
else
  printf '  %s✗%s CV PDF not served correctly\n' "$RED" "$RESET"
  SKIPPED+=("verify: CV PDF")
fi

printf '\n'
say "Open Graph content type (must be image/png, not octet-stream):"
og_type=$(curl -sI -L --max-time 25 "https://${CUSTOM_DOMAIN}/opengraph-image" 2>/dev/null | grep -i '^content-type:' | tr -d '\r' || true)
if [[ "$og_type" == *"image/png"* ]]; then
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "${og_type:-no content-type}"
else
  printf '  %s✗%s got: %s\n' "$RED" "$RESET" "${og_type:-nothing}"
  SKIPPED+=("opengraph-image is not served as image/png — check public/_headers was deployed")
fi

printf '\n'
note "Worth doing by hand: paste the URL into LinkedIn's Post Inspector to confirm the"
note "link preview renders. https://www.linkedin.com/post-inspector/"

finish

printf '\n'
printf '  %sNext, whenever you want it:%s\n' "$BOLD" "$RESET"
printf '  • Flip the GitHub repo from private to public once v1 reads well, then add a\n'
printf '    source link to the footer.\n'
printf '  • Consignación has no source link because its GitHub repo is still empty.\n'
printf '    Push it and add repoUrl back in content/projects.ts.\n'
printf '  • MySaaS keeps its link, but its public copy is stale — some two weeks behind\n'
printf '    the working tree, and missing Directory.Packages.props.\n'
printf '\n'
